import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Provider } from "react-redux";
import { createBrowserRouter, createRoutesFromElements, Route, RouterProvider } from "react-router-dom";
import DashboardLayout from "./layouts/DashboardLayout";
import EmptyLayout from "./layouts/EmptyLayout";
import MainLayout from "./layouts/MainLayout";
import CreateGroupPage from "./pages/CreateGroupPage";
import CreatePostPage from "./pages/CreatePostPage";
import DashboardAdminPage from "./pages/DashboardAdminPage";
import DashboardGroupPage from "./pages/DashboardGroupPage";
import DashboardOverviewPage from "./pages/DashboardOverviewPage";
import DashboardPage from "./pages/DashboardPage";
import DashboardUserPage from "./pages/DashboardUserPage";
import DashboardReportPage from "./pages/DashboardReportPage";
import FolderPage from "./pages/FolderPage";
import GroupPage from "./pages/GroupPage";
import HomePage from "./pages/HomePage";
import LoginPage from "./pages/LoginPage";
import NotFoundPage from "./pages/NotFoundPage";
import PostDetailPage from "./pages/PostDetailPage";
import ProfilePage from "./pages/ProfilePage";
import SettingPage from "./pages/SettingPage";
import SignUpPage from "./pages/SignUpPage";
import UserPage from "./pages/UserPage";
import { store } from "./redux/store";
import { Toaster } from "@/components/ui/toaster";
import ProtectedRoute from "./layouts/ProtectedLayout";
import PostsPage from "./pages/PostsPage";
import EditPostPage from "./pages/EditPostPage";
import UserSearchPage from "./pages/UserSearchPage";
import DashboardCategoriesPage from "./pages/DashboardCategoriesPage";
const router = createBrowserRouter(createRoutesFromElements(_jsxs(Route, { path: "/", element: _jsx(EmptyLayout, {}), children: [_jsx(Route, { path: "login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "signup", element: _jsx(SignUpPage, {}) }), _jsx(Route, { path: "/", element: _jsx(ProtectedRoute, {}), children: _jsxs(Route, { path: "/", element: _jsx(MainLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(HomePage, {}) }), _jsx(Route, { path: "users", element: _jsx(UserSearchPage, {}) }), _jsx(Route, { path: "tag/:tag", element: _jsx(PostsPage, {}) }), _jsxs(Route, { path: "profile", children: [_jsx(Route, { index: true, element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: "setting", element: _jsx(SettingPage, {}) })] }), _jsx(Route, { path: "create-post", element: _jsx(CreatePostPage, {}) }), _jsx(Route, { path: "create-group", element: _jsx(CreateGroupPage, {}) }), _jsx(Route, { path: "post/edit/:postId", element: _jsx(EditPostPage, {}) }), _jsx(Route, { path: "post/:postId", element: _jsx(PostDetailPage, {}) }), _jsx(Route, { path: "group/:groupId", element: _jsx(GroupPage, {}) }), _jsx(Route, { path: "user/:userId", element: _jsx(UserPage, {}) }), _jsx(Route, { path: "/folder/:id", element: _jsx(FolderPage, {}) }), _jsxs(Route, { path: "dashboard", element: _jsx(DashboardLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "overview", element: _jsx(DashboardOverviewPage, {}) }), _jsx(Route, { path: "user", element: _jsx(DashboardUserPage, {}) }), _jsx(Route, { path: "report", element: _jsx(DashboardReportPage, {}) }), _jsx(Route, { path: "group", element: _jsx(DashboardGroupPage, {}) }), _jsx(Route, { path: "admin", element: _jsx(DashboardAdminPage, {}) }), _jsx(Route, { path: "categories", element: _jsx(DashboardCategoriesPage, {}) })] }), _jsx(Route, { path: "/*", element: _jsx(NotFoundPage, {}) })] }) })] })));
function App() {
    return (_jsxs(Provider, { store: store, children: [_jsx(RouterProvider, { router: router }), _jsx(Toaster, {})] }));
}
export default App;
